#Generated by bots open source edi translator.
from bots.botsconfig import *
structure = [
{ID: 'Document', MIN: 1, MAX: 1, LEVEL: [
    {ID: 'CstmrPmtStsRpt', MIN: 1, MAX: 1, LEVEL: [
        {ID: 'GrpHdr', MIN: 1, MAX: 1, LEVEL: [
            {ID: 'InitgPty', MIN: 0, MAX: 1, LEVEL: [
                {ID: 'Id', MIN: 0, MAX: 99999, LEVEL: [
                    {ID: 'OrgId', MIN: 0, MAX: 99999, LEVEL: [
                        {ID: 'Othr', MIN: 0, MAX: 99999},
                    ]},
                ]},
            ]},
            {ID: 'DbtrAgt', MIN: 0, MAX:1, LEVEL: [
                {ID: 'FinInstnId', MIN: 0, MAX:99999, LEVEL: [
                    {ID: 'ClrSysMmbId', MIN: 0, MAX: 99999},
                    {ID: 'PstlAdr', MIN: 0, MAX: 99999},
                ]},
            ]},
            {ID: 'CdtrAgt', MIN: 0,MAX: 1, LEVEL: [
                {ID: 'FinInstnId', MIN: 0, MAX: 99999, LEVEL: [
                    {ID: 'ClrSysMmbId', MIN: 0, MAX: 99999},
                    {ID: 'PstlAdr', MIN: 0, MAX: 99999},
                ]},
            ]},
        ]},
        {ID: 'OrgnlGrpInfAndSts', MIN: 1, MAX: 1, LEVEL: [
            {ID: 'StsRsnInf', MIN: 0, MAX: 99999, LEVEL: [
                {ID: 'Orgtr', MIN: 0, MAX: 99999, LEVEL:[
                    {ID: 'PstlAdr', MIN: 0, MAX: 99999},
                    {ID: 'Id', MIN: 0, MAX: 99999, LEVEL: [
                        {ID: 'OrgId', MIN: 0, MAX: 99999, LEVEL: [
                            {ID: 'Othr', MIN: 0, MAX: 99999},
                        ]},
                    ]},
                ]},
                {ID: 'Rsn', MIN: 0, MAX: 99999},
            ]},
        ]},
        {ID: 'OrgnlPmtInfAndSts', MIN: 0, MAX: 99999, LEVEL: [
            {ID: 'StsRsnInf', MIN: 0, MAX: 99999, LEVEL: [
                {ID: 'Orgtr', MIN: 0, MAX: 99999, LEVEL:[
                    {ID: 'PstlAdr', MIN: 0, MAX: 99999},
                    {ID: 'Id', MIN: 0, MAX: 99999, LEVEL: [
                        {ID: 'OrgId', MIN: 0, MAX: 99999, LEVEL: [
                            {ID: 'Othr', MIN: 0, MAX: 99999},
                        ]},
                    ]},
                ]},
                {ID: 'Rsn', MIN: 0, MAX: 99999},
            ]},
            {ID: 'TxInfAndSts', MIN: 0, MAX: 99999, LEVEL: [
                {ID: 'StsRsnInf', MIN: 0, MAX: 99999, LEVEL: [
                    {ID: 'Orgtr', MIN: 0, MAX: 99999, LEVEL:[
                        {ID: 'PstlAdr', MIN: 0, MAX: 99999},
                        {ID: 'Id', MIN: 0, MAX: 99999, LEVEL: [
                            {ID: 'OrgId', MIN: 0, MAX: 99999, LEVEL: [
                                {ID: 'Othr', MIN: 0, MAX: 99999},
                            ]},
                        ]},
                    ]},
                    {ID: 'Rsn', MIN: 0, MAX: 99999},
                ]},
                {ID: 'ChrgsInf', MIN: 0, MAX: 99999, LEVEL: [
                    {ID: 'Amt', MIN: 0, MAX: 99999},
                    {ID: 'Pty', MIN: 0, MAX: 99999, LEVEL: [
                        {ID: 'FinInstnId', MIN: 0, MAX: 99999, LEVEL: [
                            {ID: 'ClrSysMmbId', MIN: 0, MAX: 99999},
                            {ID: 'PstlAdr', MIN: 0, MAX: 99999},
                        ]},
                    ]},
                ]},
                {ID: 'OrgnlTxRef', MIN: 0, MAX: 99999, LEVEL: [
                    {ID: 'Amt', MIN: 0, MAX: 99999},
                    {ID: 'Dbtr', MIN: 0, MAX: 99999, LEVEL: [
                        {ID: 'PstlAdr', MIN: 0, MAX: 99999},
                        {ID: 'Id', MIN: 0, MAX: 99999, LEVEL: [
                            {ID: 'OrgId', MIN: 0, MAX: 99999, LEVEL: [
                                {ID: 'Othr', MIN: 0, MAX: 99999},
                            ]},
                        ]},
                    ]},
                    {ID: 'DbtrAcct', MIN: 0, MAX: 99999, LEVEL: [
                        {ID: 'Id', MIN: 0, MAX: 99999, LEVEL: [
                            {ID: 'Othr', MIN: 0, MAX: 99999},
                        ]},
                    ]},
                    {ID: 'DbtrAgt', MIN: 0, MAX: 99999, LEVEL: [
                        {ID: 'FinInstnId', MIN: 0, MAX: 99999, LEVEL: [
                            {ID: 'ClrSysMmbId', MIN: 0, MAX: 99999},
                            {ID: 'PstlAdr', MIN: 0, MAX: 99999},
                        ]},
                    ]},
                    {ID: 'CdtrAgt', MIN: 0, MAX: 99999, LEVEL: [
                        {ID: 'FinInstnId', MIN: 0, MAX: 99999, LEVEL: [
                            {ID: 'ClrSysMmbId', MIN: 0, MAX: 99999},
                            {ID: 'PstlAdr', MIN: 0, MAX: 99999},
                        ]},
                    ]},
                    {ID: 'Cdtr', MIN: 0, MAX: 99999, LEVEL: [
                        {ID: 'PstlAdr', MIN: 0, MAX: 99999},
                        {ID: 'Id', MIN: 0, MAX: 99999, LEVEL: [
                            {ID: 'OrgId', MIN: 0, MAX: 99999, LEVEL: [
                                {ID: 'Othr', MIN: 0, MAX: 99999},
                            ]},
                        ]},
                    ]},
                    {ID: 'CdtrAcct', MIN: 0, MAX: 99999, LEVEL: [
                        {ID: 'Id', MIN: 0, MAX: 99999, LEVEL: [
                            {ID: 'Othr', MIN: 0, MAX: 99999},
                        ]},
                    ]},
                ]},
            ]},
        ]},
    ]},
]},
]

recorddefs = {
    'Amt':
        [
            ['BOTSID', 'M', 256, 'AN'],
            ['InstdAmt', 'C', 256, 'AN'],
            ['InstdAmt__Ccy', 'C', 256, 'AN'],
        ],
    'Cdtr':
        [
            ['BOTSID', 'M', 256, 'AN'],
            ['Nm', 'C', 256, 'AN'],
        ],
    'CdtrAcct':
        [
            ['BOTSID', 'M', 256, 'AN'],
        ],
    'CdtrAgt':
        [
            ['BOTSID', 'M', 256, 'AN'],
        ],
    'ChrgsInf':
        [
            ['BOTSID', 'M', 256, 'AN'],
        ],
    'ClrSysMmbId':
        [
            ['BOTSID', 'M', 256, 'AN'],
            ['MmbId', 'C', 256, 'AN'],
        ],
    'CstmrPmtStsRpt':
        [
            ['BOTSID', 'M', 256, 'AN'],
        ],
    'Dbtr':
        [
            ['BOTSID', 'M', 256, 'AN'],
            ['Nm', 'C', 256, 'AN'],
        ],
    'DbtrAcct':
        [
            ['BOTSID', 'M', 256, 'AN'],
        ],
    'DbtrAgt':
        [
            ['BOTSID', 'M', 256, 'AN'],
        ],
    'Document':
        [
            ['BOTSID', 'M', 256, 'AN'],
        ],
    'FinInstnId':
        [
            ['BOTSID', 'M', 256, 'AN'],
            ['BIC', 'C', 256, 'AN'],
        ],
    'GrpHdr':
        [
            ['BOTSID', 'M', 256, 'AN'],
            ['MsgId', 'C', 256, 'AN'],
            ['CreDtTm', 'C', 256, 'AN'],
        ],
    'Id':
        [
            ['BOTSID', 'M', 256, 'AN'],
            ['IBAN', 'C', 256, 'AN'],
        ],
    'InitgPty':
        [
            ['BOTSID', 'M', 256, 'AN'],
        ],
    'OrgId':
        [
            ['BOTSID', 'M', 256, 'AN'],
            ['BICOrBEI', 'C', 256, 'AN'],
        ],
    'OrgnlGrpInfAndSts':
        [
            ['BOTSID', 'M', 256, 'AN'],
            ['OrgnlMsgId', 'C', 256, 'AN'],
            ['OrgnlMsgNmId', 'C', 256, 'AN'],
            ['OrgnlCreDtTm', 'C', 256, 'AN'],
            ['OrgnlNbOfTxs', 'C', 256, 'AN'],
            ['OrgnlCtrlSum', 'C', 256, 'AN'],
            ['GrpSts', 'C', 256, 'AN'],
        ],
    'OrgnlPmtInfAndSts':
        [
            ['BOTSID', 'M', 256, 'AN'],
            ['OrgnlPmtInfId', 'C', 256, 'AN'],
            ['OrgnlNbOfTxs', 'C', 256, 'AN'],
            ['OrgnlCtrlSum', 'C', 256, 'AN'],
            ['PmtInfSts', 'C', 256, 'AN'],
        ],
    'OrgnlTxRef':
        [
            ['BOTSID', 'M', 256, 'AN'],
            ['ReqdColltnDt', 'C', 256, 'AN'],
            ['ReqdExctnDt', 'C', 256, 'AN'],
        ],
    'Orgtr':
        [
            ['BOTSID', 'M', 256, 'AN'],
            ['Nm', 'C', 256, 'AN'],
        ],
    'Othr':
        [
            ['BOTSID', 'M', 256, 'AN'],
            ['Id', 'C', 256, 'AN'],
        ],
    'PstlAdr':
        [
            ['BOTSID', 'M', 256, 'AN'],
            ['StrtNm', 'C', 70, 'AN'],
            ['BldgNb', 'C', 16, 'AN'],
            ['PstCd', 'C', 16, 'AN'],
            ['TwnNm', 'C', 35, 'AN'],
            ['CtrySubDvsn', 'C', 35, 'AN'],
            ['Ctry', 'C', 2, 'AN'],
            ['AdrLine', 'C', 70, 'AN'],
        ],
    'Pty':
        [
            ['BOTSID', 'M', 256, 'AN'],
        ],
    'Rsn':
        [
            ['BOTSID', 'M', 256, 'AN'],
            ['Cd', 'C', 256, 'AN'],
            ['Prtry', 'C', 256, 'AN'],
        ],
    'StsRsnInf':
        [
            ['BOTSID', 'M', 256, 'AN'],
            ['AddtlInf', 'C', 256, 'AN'],
        ],
    'TxInfAndSts':
        [
            ['BOTSID', 'M', 256, 'AN'],
            ['StsId', 'C', 256, 'AN'],
            ['OrgnlInstrId', 'C', 256, 'AN'],
            ['OrgnlEndToEndId', 'C', 256, 'AN'],
            ['TxSts', 'C', 256, 'AN'],
            ['AccptncDtTm', 'C', 256, 'AN'],
            ['AcctSvcrRef', 'C', 256, 'AN'],
            ['ClrSysRef', 'C', 256, 'AN'],
        ],
}
