#Generated by bots open source edi translator.
from bots.botsconfig import *

syntax = {
    'indented':True
}

structure = [
{ID:'Document',MIN:0,MAX:99999,LEVEL:[
    {ID:'CstmrCdtTrfInitn',MIN:0,MAX:99999,LEVEL:[
        {ID:'GrpHdr',MIN:0,MAX:99999,LEVEL:[
            {ID:'Authstn',MIN:0,MAX:1},
            {ID:'NbOfTxs',MIN:0,MAX:1},
            {ID:'CtrlSum',MIN:0,MAX:1},
            {ID:'InitgPty',MIN:0,MAX:99999,LEVEL:[
                {ID:'Id',MIN:0,MAX:99999,LEVEL:[
                    {ID:'OrgId',MIN:0,MAX:99999,LEVEL:[
                        {ID:'Othr',MIN:0,MAX:99999},
                    ]},
                ]},
            ]},
        ]},
        {ID:'PmtInf',MIN:0,MAX:99999,LEVEL:[
            {ID:'PmtTpInf',MIN:0,MAX:99999,LEVEL:[
                {ID:'SvcLvl',MIN:0,MAX:99999},
                {ID:'LclInstrm',MIN:0,MAX:99999},
            ]},
            {ID:'ReqdExctnDt',MIN:0,MAX:1},
            {ID:'Dbtr',MIN:0,MAX:99999,LEVEL:[
                {ID:'PstlAdr',MIN:0,MAX:99999},
                {ID:'Id',MIN:0,MAX:99999,LEVEL:[
                    {ID:'OrgId',MIN:0,MAX:99999,LEVEL:[
                        {ID:'Othr',MIN:0,MAX:99999},
                    ]},
                ]},
            ]},
            {ID:'DbtrAcct',MIN:0,MAX:99999,LEVEL:[
                {ID:'Id',MIN:0,MAX:99999,LEVEL:[
                    {ID:'Othr',MIN:0,MAX:99999},
                ]},
            ]},
            {ID:'DbtrAgt',MIN:0,MAX:99999,LEVEL:[
                {ID:'FinInstnId',MIN:0,MAX:99999,LEVEL:[
                    {ID:'ClrSysMmbId',MIN:0,MAX:99999},
                    {ID:'PstlAdr',MIN:0,MAX:99999},
                ]},
            ]},
            {ID:'ChrgBr',MIN:0,MAX:1},
            {ID:'CdtTrfTxInf',MIN:0,MAX:99999,LEVEL:[
                {ID:'PmtId',MIN:0,MAX:1},
                {ID:'Amt',MIN:0,MAX:1},
                {ID:'CdtrAgt',MIN:0,MAX:1,LEVEL:[
                    {ID:'FinInstnId',MIN:0,MAX:1,LEVEL:[
                        {ID:'ClrSysMmbId',MIN:0,MAX:1},
                        {ID:'PstlAdr',MIN:0,MAX:1},
                    ]},
                ]},
                {ID:'ChqInstr',MIN:0,MAX:1,LEVEL:[
                    {ID:'DlvryMtd',MIN:0,MAX:1},
                    {ID:'DlvrTo',MIN:0,MAX:1,LEVEL:[
                        {ID:'Adr',MIN:0,MAX:1},
                    ]},
                ]},
                {ID:'Cdtr',MIN:0,MAX:1,LEVEL:[
                    {ID:'PstlAdr',MIN:0,MAX:1},
                ]},
                {ID:'CdtrAcct',MIN:0,MAX:1,LEVEL:[
                    {ID:'Id',MIN:0,MAX:1,LEVEL:[
                        {ID:'Othr',MIN:0,MAX:1},
                    ]},
                ]},
                {ID:'Purp',MIN:0,MAX:1},
                {ID:'RltdRmtInf',MIN:0,MAX:99999,LEVEL:[
                    {ID:'RmtLctnPstlAdr',MIN:0,MAX:99999,LEVEL:[
                        {ID:'Adr',MIN:0,MAX:99999},
                    ]},
                ]},
                {ID:'RmtInf',MIN:0,MAX:99999,LEVEL:[
                    {ID:'Strd',MIN:0,MAX:99999,LEVEL:[
                        {ID:'RfrdDocInf',MIN:0,MAX:1},
                        {ID:'RfrdDocAmt',MIN:0,MAX:1},
                        {ID:'CdtrRefInf',MIN:0,MAX:1},
                    ]}
                ]},
            ]},
        ]},
    ]},
]},
]

recorddefs = {
'Adr':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['Ctry', 'C', 256, 'AN'],
    ],
'Amt':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['InstdAmt', 'C', 256, 'AN'],
    ['InstdAmt__Ccy', 'C', 256, 'AN'],
    ],
'Authstn':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['Cd', 'C', 256, 'AN'],
    ],
'CdtTrfTxInf':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ],
'ChqInstr':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['ChqNb', 'C', 256, 'AN'],
    ['FrmsCd', 'C', 256, 'AN'],
    ],
'DlvryMtd':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['Cd', 'C', 256, 'AN'],
    ['Prtry', 'C', 256, 'AN'],
    ],
'DlvrTo':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['Nm', 'C', 256, 'AN'],
    ],
'Adr':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['StrtNm', 'C', 256, 'AN'],
    ['BldgNb', 'C', 256, 'AN'],
    ['PstCd', 'C', 256, 'AN'],
    ['TwnNm', 'C', 256, 'AN'],
    ['CtrySubDvsn', 'C', 256, 'AN'],
    ['Ctry', 'C', 256, 'AN'],
    ['AdrLine', 'C', 256, 'AN'],
    ],
'Cdtr':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['Nm', 'C', 256, 'AN'],
    ],
'CdtrAcct':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ],
'CdtrAgt':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ],
'ClrSysMmbId':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['MmbId', 'C', 256, 'AN'],
    ],
'CstmrCdtTrfInitn':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ],
'Dbtr':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['Nm', 'C', 256, 'AN'],
    ],
'DbtrAcct':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ],
'DbtrAgt':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ],
'Document':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['Document__xmlns', 'C', 256, 'AN'],
    ['Document__xmlns:xsi', 'C', 256, 'AN'],
    ],
'FinInstnId':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['BIC', 'C', 256, 'AN'],
    ],
'GrpHdr':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['MsgId', 'C', 256, 'AN'],
    ['CreDtTm', 'C', 256, 'AN'],
    ],
'NbOfTxs':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['BOTSCONTENT', 'C', 256, 'AN'],
    ],
'CtrlSum':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['BOTSCONTENT', 'C', 256, 'AN'],
    ],
'Id':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['IBAN', 'C', 256, 'AN'],
    ],
'InitgPty':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ],
'OrgId':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ],
'Othr':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['Id', 'C', 256, 'AN'],
    ],
'PmtId':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['InstrId', 'C', 256, 'AN'],
    ['EndToEndId', 'C', 256, 'AN'],
    ],
'PmtInf':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['PmtInfId', 'C', 256, 'AN'],
    ['PmtMtd', 'C', 256, 'AN'],
    ],
'PmtTpInf':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ],
'ReqdExctnDt':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['BOTSCONTENT', 'C', 256, 'AN'],
    ],
'ChrgBr':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['BOTSCONTENT', 'C', 256, 'AN'],
    ],
'PstlAdr':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['StrtNm', 'C', 70, 'AN'],
    ['BldgNb', 'C', 16, 'AN'],
    ['PstCd', 'C', 16, 'AN'],
    ['TwnNm', 'C', 35, 'AN'],
    ['CtrySubDvsn', 'C', 35, 'AN'],
    ['Ctry', 'C', 2, 'AN'],
    ['AdrLine', 'C', 70, 'AN'],
    ],
'Purp':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['Cd', 'C', 256, 'AN'],
    ['Prtry', 'C', 256, 'AN'],
    ],
'RltdRmtInf':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['RmtId', 'C', 256, 'AN'],
    ['RmtLctnMtd', 'C', 256, 'AN'],
    ['RmtLctnElctrncAdr', 'C', 256, 'AN'],
    ],
'RmtInf':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['Ustrd', 'C', 256, 'AN'],
    ],
'Strd':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['AddtlRmtInf', 'C', 256, 'AN'],
    ],
'RfrdDocInf':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['Tp', 'C', 256, 'AN'],
    ['Nb', 'C', 256, 'AN'],
    ['RltdDt', 'C', 256, 'AN'],
    ],
'RfrdDocAmt':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['DuePyblAmt', 'C', 256, 'AN'],
    ['DuePyblAmt__Ccy', 'C', 256, 'AN'],
    ['DscntApldAmt', 'C', 256, 'AN'],
    ['DscntApldAmt__Ccy', 'C', 256, 'AN'],
    ['CdtNoteAmt', 'C', 256, 'AN'],
    ['CdtNoteAmt__Ccy', 'C', 256, 'AN'],
    ['TaxAmt', 'C', 256, 'AN'],
    ['TaxAmt__Ccy', 'C', 256, 'AN'],
    ['RmtdAmt', 'C', 256, 'AN'],
    ['RmtdAmt__Ccy', 'C', 256, 'AN'],
    ],
'CdtrRefInf':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['Ref', 'C', 256, 'AN'],
    ],
'RmtLctnPstlAdr':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['Nm', 'C', 256, 'AN'],
    ],
'SvcLvl':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['Cd', 'C', 256, 'AN'],
    ],
'LclInstrm':
    [
    ['BOTSID', 'M', 256, 'AN'],
    ['Cd', 'C', 256, 'AN'],
    ['Prtry', 'C', 256, 'AN'],
    ],
}
